language: python
python:
  - "2.6"
  - "2.7"
  - "3.3"
  - "3.4"
env:
  - FLASK=0.10
  - FLASK=0.10.1
  - FLASK=0.10 speaklater
  - FLASK=0.10.1 speaklater
install:
  - pip install Flask==$FLASK
  - pip install pep8
before_script:
 - pep8 flask_json.py
script: nosetests
